import React from "react";
import TopNavbar from "./../../component/nav/TopNavbar";
import { useState } from "react";
import Footer from "../../component/partials/Footer";
import * as ICONS from "../../assets/icons";

const PrivacyPolicy = () => {
  const [navBarOpen, setNavBarOpen] = useState(false);
  return (
    <div className='h-screen w-screen overflow-scroll'>
      <TopNavbar navBarOpen={navBarOpen} setNavBarOpen={setNavBarOpen} />

      {/* Main */}
      <main className='mt-20 md:mt-15  relative'>
        <div className=''>
          <div className='privacy_policy p-4 pt-10 md:w-[75%] md:mx-auto'>
            <h2 className='text-isSkyBlue400 text-lg font-medium md:text-2xl md:pb-3 md:border-b md:border-b-isPurple300'>
              Our Privacy Policy
            </h2>
            <div className='mt-4 font-inter font-normal text-[15px]'>
              <p>
                <span className='font-semibold'>
                  <i>PayTyme</i>
                </span>{" "}
                ("we," "our," or "us") is committed to protecting your privacy
                This Privacy Policy explains how your personal information is
                collected, used, and disclosed by PayTyme.
              </p>
              <p className='mt-4'>
                This Privacy Policy applies to our application named PayTyme and
                its associated subdomains (collectively, our "Service"). By
                accessing or using our Service, you signify that you have read,
                understood, and agree to our collection, storage, use, and
                disclosure of your personal information as described in this
                Privacy Policy and our Terms of Service.
              </p>
            </div>
          </div>
          <section className='bg-[#F5F5FD] p-4 py-8 mt-10 md:pt-16'>
            <div className='md:w-[75%] md:mx-auto font-inter font-normal text-[15px]'>
              <div className="mb-6 md:pt-5 md:border-t md:border-t-isPurple300">
                <div className="flex justify-between items-center">
                  <h2 className='text-isSkyBlue400 text-lg font-medium md:text-2xl '>
                    Definitions and key terms
                  </h2>
                  <span className="cursor-pointer text-2xl"><ICONS.AiOutlineMinus/></span>
                </div>
                <div className='hidde mt-4 font-inter font-normal text-[15px]'>
                  <p>
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
                  </p>
                </div>
              </div>
              <div className="hidde">
                <ul className="pl-6 md:pl-10">
                  <li className="list-disc">
                  <span className="font-bold">Cookie:</span> small amount of data generated by a website and saved by your web browser. It is used to identify your browser provide analytics remember information about vou such as vour language preference or login information.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Company:</span> when this policy mentions "Company," "we," "us," or "our," it refers to PayTyme that is responsible for your information under this Privacy Policy.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Country:</span> where PayTyme or the owners/founders of PayTyme are based, in this case is Nigeria.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Customer:</span> refers to the company, organization or person that signs up to use the PayTyme Service to manage the relationships with your consumers or service users.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Device:</span>  any internet connected device such as a phone, tablet, computer or any other device that can be used to visit PayTyme and use the services.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">IP address:</span>  Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Personnel:</span>  refers to those individuals who are employed by PayTyme or are under contract to perform a service on behalf of one of the parties.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Personal Data:</span>  any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Service:</span>  refers to the service provided by PayTyme as described in the relative terms (if available) and on this platform.
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Third-party service:</span>   refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">Website:</span>   PayTyme's site, which can be accessed via this URL:
                  </li>
                  <li className="list-disc mt-4">
                  <span className="font-bold">You:</span>   a person or entity that is registered with PayTyme to use the Services.
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </div>
      </main>
      {/* End Main */}

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
